sonar.projectKey=aceest-fitness-app
sonar.projectName=ACEest Fitness App
sonar.sourceEncoding=UTF-8

sonar.sources=.
sonar.tests=tests

sonar.exclusions=venv/**,__pycache__/**,.pytest_cache/**,.git/**,k8s/**,versions/**,docker-compose/**,templates/**
sonar.coverage.exclusions=tests/**
sonar.python.coverage.reportPaths=coverage.xml
